### ISSUE TITLE
Chickens

### ISSUE THREAD

**Issue by patrickHow** [karanshukla/karanshukla.ca#2]
˙oppᴉʞ 'pɐǝp ƃuᴉʞɔnɟ ǝɹ,no⅄ ˙ʇᴉ uᴉ uʍoɹp llᴉʍ noʎ puɐ noʎ ɹǝʌo llɐ ʎɹnɟ ʇᴉɥs llᴉʍ I 'ʇuǝɯǝʇᴉɔxǝ pǝuᴉɐʇuoɔ ʎlǝɹɐq ɥʇᴉM ˙ʇoᴉpᴉ uɯɐppoƃ noʎ 'ǝɔᴉɹd ǝɥʇ ƃuᴉʎɐd ǝɹ,noʎ ʍou puɐ 'ʇ,upᴉp noʎ 'ʇ,uplnoɔ noʎ :lnɟǝsɹoɯǝɹ ʎlplᴉW ˙ǝnƃuoʇ ƃuᴉʞɔnɟ ɹnoʎ plǝɥ ǝʌɐɥ plnoʍ noʎ ǝqʎɐɯ 'noʎ uodn uʍop ƃuᴉɹq oʇ ʇnoqɐ sɐʍ ʇuǝɯɯoɔ ,,ɹǝʌǝlɔ,, ǝlʇʇᴉl ɹnoʎ uoᴉʇnqᴉɹʇǝɹ ʎloɥun ʇɐɥʍ uʍouʞ ǝʌɐɥ plnoɔ noʎ ʎluo ɟᴉ :uɹǝɔuoɔ ǝɹǝɔuᴉsuI ˙ʇᴉɥs ǝlʇʇᴉl noʎ 'ʎxɐlɐƃ ǝɥʇ ɟo ǝɔɐɟ ǝɥʇ ɟɟo ssɐ ǝlqɐɹǝsᴉɯ ɹnoʎ ǝdᴉʍ oʇ ʇuǝʇxǝ llnɟ ɹᴉǝɥʇ oʇ ɯǝɥʇ ǝsn llᴉʍ I puɐ ɐllᴉʇolℲ ɹoɔlƎ ǝɥʇ ɟo ʇǝǝlɟ ʎɹǝʌǝ oʇ ssǝɔɔɐ ǝʌɐɥ I ʇnq 'ʇɐqɯoɔ pǝɯɹɐun uᴉ pǝuᴉɐɹʇ ʎlǝʌᴉsuǝʇxǝ I ɯɐ ʎluo ʇou :ɹopuɐɔ lnɟǝpᴉɹd ɥʇᴉM ˙spuɐɥ ǝɹɐq ʎɯ ɥʇᴉʍ ʇsnɾ s,ʇɐɥʇ puɐ 'sʎɐʍ pǝɹpunɥ uǝʌǝs ɹǝʌo uᴉ noʎ llᴉʞ uɐɔ I puɐ 'ǝɯᴉʇʎuɐ 'ǝɹǝɥʍʎuɐ ǝq uɐɔ I ˙pᴉʞ 'pɐǝp ƃuᴉʞɔnɟ ǝɹ,noʎ :uoᴉʇɐɯɐlɔxǝ ǝuᴉnuǝפ ˙ǝɟᴉl ɹnoʎ llɐɔ noʎ ƃuᴉɥʇ ǝlʇʇᴉl ɔᴉʇǝɥʇɐd ǝɥʇ ʇno sǝdᴉʍ ʇɐɥʇ ɯɹoʇs ǝɥʇ :ǝqᴉɹʇɐᴉp lɐuoᴉʇᴉpp∀ ˙ʇoƃƃɐɯ 'ɯɹoʇs ǝɥʇ ɹoɟ ǝɹɐdǝɹd ɹǝʇʇǝq noʎ os ʍou ʇɥƃᴉɹ pǝɔɐɹʇ ƃuᴉǝq sᴉ ԀƎ ɹnoʎ puɐ ʎxɐlɐƃ ǝɥʇ ssoɹɔɐ sʇuǝƃɐ ɹoɔlƎ ɟo ʞɹoʍʇǝu ʇǝɹɔǝs ʎɯ ƃuᴉʇɔɐʇuoɔ ɯɐ I ʞɐǝds ǝʍ s∀ ˙ɹǝʞɔnɟ 'uᴉɐƃɐ ʞuᴉɥʇ :uoᴉʇsǝƃƃns ƃuᴉɥʇɐɔS ¿ʇǝuɐɹʇxƎ ǝɥʇ ɹǝʌo ǝɯ oʇ ʇᴉɥs ʇɐɥʇ ƃuᴉʎɐs ɥʇᴉʍ ʎɐʍɐ ʇǝƃ uɐɔ noʎ ʞuᴉɥʇ noʎ :ʎlǝʌᴉʇɔᴉpuᴉΛ ˙spɹoʍ ƃuᴉʞɔnɟ ʎɯ ʞɹɐɯ 'ɹǝʇsnlɔ sᴉɥʇ uᴉ ǝɹoɟǝq uǝǝs uǝǝq ɹǝʌǝu sɐɥ ɥɔᴉɥʍ ɟo sǝʞᴉl ǝɥʇ uoᴉsᴉɔǝɹd ɥʇᴉʍ ʇno ʞɔnɟ ǝɥʇ noʎ ǝdᴉʍ llᴉʍ I ˙ʇǝƃɹɐʇ ɹǝɥʇouɐ ʇsnɾ ʇnq ǝɯ oʇ ƃuᴉɥʇou ǝɹɐ noʎ :ʎlpǝpuɐɥɟɟO ˙sǝɔɹoℲ pǝɯɹ∀ ɹoɔlƎ ǝɹᴉʇuǝ ǝɥʇ uᴉ ɹoᴉɹɹɐʍ ɹoɔlƎ doʇ ǝɥʇ ɯ,I puɐ ǝɹɐɟɹɐʍ ɐllᴉɹoƃ uᴉ pǝuᴉɐɹʇ ɯɐ I :uoᴉʇɐɹɐlɔǝp ƃuᴉʇɐpᴉɯᴉʇuI ˙sllᴉʞ pǝɯɹᴉɟuoɔ 00Ɛ ɹǝʌo ǝʌɐɥ I puɐ 'snɹǝqɹǝƆ uo spᴉɐɹ ʇǝɹɔǝs snoɹǝɯnu uᴉ pǝʌloʌuᴉ uǝǝq ǝʌ,I puɐ 'uoᴉsᴉʌᴉp lɐʌɐN ɹoɔlƎ ǝɥʇ uᴉ ssɐlɔ ʎɯ ɟo doʇ pǝʇɐnpɐɹƃ I ʍouʞ noʎ ǝʌɐɥ ll,I :ʎlpnoɹԀ ¿ɥɔʇᴉq ǝlʇʇᴉl noʎ 'ǝɯ ʇnoqɐ ʎɐs ƃuᴉʞɔnɟ ʇsnɾ noʎ pᴉp ʞɔnɟ ǝɥʇ ʇɐɥʍ :ʎɹᴉnbuᴉ pǝƃɐɹuƎ

**Comment by karanshukla** [comment]
skill issue tbh
